### ISSUE TITLE
ninja-sign-ruby => freee-sign-ruby へのリネーム

### ISSUE THREAD

**Issue by yokozawa0701** [yokozawa0701/freee-sign-ruby#20]

**Comment by noriyotcp** [comment]
横沢さんがやった。エンドポイントや`spec/freee-sign_spec.rb` 内のテスト以外では `ninja-sign` はない・・・と思ったら `sig/` のほうに残ってたのでプルリクは出した https://github.com/yokozawa0701/freee-sign-ruby/pull/25

**Comment by noriyotcp** [comment]
#25 はマージ済み。これでリネーム完了かな？
